version: '3.7'

services:
  app:
    build:
      context: ./
    ports:
      - "8888:8888"
    networks:
      - server-net
    depends_on:
      - db
    volumes:
      - shared-data:/shared-data
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    build:
      context: ./BackupDocker
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - server-net
    volumes:
      - shared-data:/shared-data
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  shared-data:

networks:
  server-net:
