version: '3'

services:
  app:
    build: ./
    ports:
      - "8888:8888"
    networks:
      - server-net
    depends_on:
      - db
    volumes:
      - shared-data:/shared-data

  db:
    # will build ./BackupDocker/Dockerfile
    build: ./BackupDocker/
    ports:
      - "3306:3306"
    networks:
      - server-net
    volumes:
      - shared-data:/shared-data

volumes:
 shared-data:

networks:
  server-net:
