version: '3'

services:
  app:
    build: ./
    ports:
      - "8888:8888"
    networks:
      - server-net
    depends_on:
      - db
    volumes:
      - shared-data:/shared-data
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    build: ./BackupDocker
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - server-net
    volumes:
      - shared-data:/shared-data

volumes:
 shared-data:

networks:
  server-net: