version: '3'

services:
  app:
    build: ./
    ports:
      - "8888:8888"
    networks:
      - server-net
    depends_on:
      - db

  db:
    # will build ./BackupDocker/Dockerfile
    build: ./BackupDocker/
    ports:
      - "3306:3306"
    networks:
      - server-net


networks:
  server-net:
